---
- name: Raport włączonych usług na hoście zdalnym
  hosts: all
  gather_facts: no
  become: yes
  tasks:

    - name: Utwórz katalog na raporty, jeśli nie istnieje
      file:
        path: /home/dominik/Ansible_Reports
        state: directory
        mode: '0755'
        owner: dominik
        group: dominik

    - name: Pobierz listę włączonych usług
      shell: systemctl list-unit-files --state=enabled
      register: enabled_services

    - name: Zapisz raport do pliku z datą i godziną
      vars:
        current_time: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"
      copy:
        content: "{{ enabled_services.stdout }}"
        dest: "/home/dominik/Ansible_Reports/{{ current_time }}.txt"
        owner: dominik
        group: dominik
        mode: '0644'
