---
- name: Raport wyłączonych usług na hoście zdalnym
  hosts: all
  gather_facts: no
  become: yes
  tasks:

    - name: Utwórz katalog na raporty, jeśli nie istnieje
      file:
        path: /home/dominik/Ansible_Reports
        state: directory
        mode: '0755'
        owner: dominik
        group: dominik

    - name: Pobierz listę wyłączonych usług
      shell: systemctl list-unit-files --state=disabled
      register: disabled_services

    - name: Zapisz raport do pliku z datą i godziną
      copy:
        content: "{{ disabled_services.stdout }}"
        dest: "/home/dominik/Ansible_Reports/disabled_services_{{ ansible_date_time.date }}_{{ ansible_date_time.time | regex_replace(':','-') }}.txt"
        owner: dominik
        group: dominik
        mode: '0644'
